version: "3.3"

services: 
  api:
    ports:
      - 8080:8080
    build: 
      context: ./
      dockerfile: ./Dockerfile
    networks: 
      - default-network

networks: 
  default-network:
    driver: bridge